### ISSUE TITLE
Accented or special characters

### ISSUE THREAD

**Issue by TheFireRed** [kcghost/CAH-Builder#1]
It doesn't seem to recognise special characters from foreign languages. Interrogative pronouns in Spanish all include accented characters. I also thought about using the opening question mark, but to no avail.

Consequently, it doesn't know the difference between a black card and a white card.

`if(match(tolower(quotes_strip),/(¿|qué|cómo|cuándo|dónde).+?\?$/) || match($$0,/[_]/) || match(quotes_strip,/haiku/)) {`

**Comment by kcghost** [comment]
Sorry for the late reply, and thanks for bringing this to my attention, I hadn't thought about supporting different languages. I just added spanish interrogative word bases in commit 103b34efb313029f0c83c5080c48aaf04758b3ea, it is a similar change to the one you proposed here. I don't know spanish well, so I hope there are no problems. As far as I understand, there is still an ending question mark (as well as beginning ), so it should work well.

The accented interrogative words worked well in my tests, so I am not sure why you had an issue. Perhaps make sure to start from scratch and re-process the cards (make clean), and make sure the text file is UTF-8. If there is still a problem...perhaps your 'gawk' does not support unicode? I am using 4.1.3.

**Comment by TheFireRed** [comment]
Definitely, I did something wrong in my machine and messed it up. After restarting from the beginning and adding the `¿` character it worked flawlessly. Thank you for your time!
